server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: django-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          __path__: ../.logs/django.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            name: name
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05,000"
