name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY:  ${{ secrets.SECRET_KEY }}
      FERNET_KEY: ${{ secrets.FERNET_KEY }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar migrações
        run: python manage.py migrate

      - name: Rodar testes
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # só roda se os testes passarem
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FERNET_KEY: ${{ secrets.FERNET_KEY }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/${{ secrets.SERVER_USER }}/v3-test
            git pull origin main
            pip install -r requirements.txt
            source venv/bin/activate
            export SECRET_KEY=${{ secrets.SECRET_KEY }}
            export FERNET_KEY=${{ secrets.FERNET_KEY }}
            python manage.py migrate
